# Generated by Django 4.0.1 on 2022-09-27 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_category_image1_alter_category_image2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardobject',
            old_name='id',
            new_name='cardid',
        ),
    ]
