# Generated by Django 4.1 on 2022-08-29 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_blog_news_partner_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_uz', models.TextField(blank=True, max_length=2000, null=True)),
                ('about_ru', models.TextField(blank=True, max_length=2000, null=True)),
                ('about_en', models.TextField(blank=True, max_length=2000, null=True)),
                ('link', models.URLField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='partner',
            name='name_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='name_ru',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='name_uz',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
