# Generated by Django 4.1 on 2022-08-31 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_remove_partner_name_en_remove_partner_name_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
